### ISSUE TITLE
It does not connect

### ISSUE THREAD

**Issue by jamalskiy** [royalmo/openvpn-manager#1]
I created a file through the bot, logged into the openvpn program, but it does not connect

**Comment by royalmo** [comment]
Please provide me details of your environment so I might try to reproduce it: OS, python version, openvpn version, ...

Did you installed openvpn through the openvpn_install.sh script?

Once openvpn configured, did you add the port redirection to your home router? The UDP port you specified during install needs to be redirected from your home router to your device (if your ISP is using CG-NAT this might not be possible to do).

**Comment by jamalskiy** [comment]
sorry for the long answer, everything works
